// ============================================
// SET 3 QUESTIONS DATA
// ============================================
const quizDataSet3 = {
    sections: [
        {
            id: "A", title: "System, Elements, Interconnections and Purpose", subtitle: "10 Case-Based MCQs",
            caseParagraph: `A university wants to improve student learning. At first, the administration thinks only about physical things like classrooms, projectors, benches, and attendance registers. Later, they realize that invisible factors like student motivation, teacher-student trust, classroom culture, rules, feedback, and peer pressure are also affecting learning. For example, even when classrooms are good, students may not attend if teaching quality is poor or if they believe classes are not useful. The university also notices that its stated purpose is "deep learning," but the actual behaviour of the system is focused mainly on marks, attendance, and exams.`,
            type: "mcq",
            questions: [
                { id:"A1", text:"In this case, why is the university considered a system?", options:["Because it has many connected parts that interact and produce learning behaviour","Because it only has buildings and classrooms","Because students and teachers do not affect each other","Because it has no purpose or structure"], correct:0 },
                { id:"A2", text:"Classrooms, benches, projectors, and attendance registers are examples of:", options:["Tangible elements because they are physical parts of the system","Intangible elements because they are invisible beliefs","Mental models because they are assumptions","Feedback loops because they return output to input"], correct:0 },
                { id:"A3", text:"Motivation, trust, culture, and peer pressure are important because they are:", options:["Intangible elements that strongly affect system behaviour","Physical flows that can always be touched","Closed systems with no environment","Only events, not part of the system"], correct:0 },
                { id:"A4", text:`"Teaching quality affects student motivation, and motivation affects attendance" mainly describes:`, options:["Interconnections between system elements","Only tangible elements","A closed system","A source and sink"], correct:0 },
                { id:"A5", text:"If student feedback reaches teachers and teachers improve their methods, this is an example of:", options:["Information flow influencing decisions","Physical flow of materials","A stock that cannot change","A system boundary only"], correct:0 },
                { id:"A6", text:"If books move from library shelves to students and back again, this is closer to:", options:["Physical or material flow","Mental model only","Nash equilibrium","Paradigm shift"], correct:0 },
                { id:"A7", text:`The university says its purpose is "deep learning," but students mainly study for marks. This difference shows:`, options:["Stated purpose and observed purpose may be different","All systems have no purpose","Physical elements are always more important than invisible elements","Closed systems are common in education"], correct:0 },
                { id:"A8", text:"The actual behaviour of focusing on marks and attendance shows the system's:", options:["Observed purpose","Stated purpose only","Environment only","Tangible flow only"], correct:0 },
                { id:"A9", text:"Which statement best follows Systems Thinking?", options:["Learning depends on relationships between rules, motivation, teaching quality, culture, and exams","Learning depends only on classroom benches","Students alone are responsible for all outcomes","Systems can be understood without interconnections"], correct:0 },
                { id:"A10", text:"If the university changes only projectors but ignores motivation and feedback, the change may fail because:", options:["Intangible elements and interconnections also shape learning behaviour","Physical elements are never part of systems","Motivation cannot influence learning","Purpose is not important in systems"], correct:0 }
            ]
        },
        {
            id: "B", title: "Boundary, Environment, Open Systems & Nested Systems", subtitle: "10 Case-Based MCQs",
            caseParagraph: `A city faces traffic congestion every morning. The traffic department first defines the problem narrowly as "too many cars on roads" and decides to build more roads. However, congestion returns after some time. Later, planners widen the system boundary and include public transport, office timings, school timings, housing locations, fuel prices, parking rules, and people's preference for private cars. They also realize that the traffic system is part of larger nested systems such as urban planning, economy, environment, and public policy. The city cannot fully control external factors like fuel prices and population migration, but these factors still influence traffic.`,
            type: "mcq",
            questions: [
                { id:"B1", text:"When the traffic department first includes only cars and roads, it is using:", options:["A narrow system boundary","A wide nested system view","A mental model transformation","Dynamic equilibrium"], correct:0 },
                { id:"B2", text:"Why may building more roads fail as a long-term solution?", options:["Because it ignores wider factors like public transport, office timings, and private car preference","Because roads are not tangible elements","Because traffic has no interconnections","Because cities are closed systems"], correct:0 },
                { id:"B3", text:"Including public transport, housing locations, and office timings means planners are:", options:["Widening the system boundary","Removing all variables","Ignoring the environment","Creating a closed system"], correct:0 },
                { id:"B4", text:"Fuel prices and population migration are examples of:", options:["Environmental factors that influence the system from outside","Internal elements fully controlled by the traffic department","Feedback loops inside one car","System traps only"], correct:0 },
                { id:"B5", text:"The traffic system interacting with economy, environment, and public policy shows that it is:", options:["An open system","A closed system","A single object","A static object with no behaviour"], correct:0 },
                { id:"B6", text:"A traffic signal network inside the larger city transport system can be called:", options:["A subsystem","A paradigm","A mental model","A dominant strategy"], correct:0 },
                { id:"B7", text:"City traffic being influenced by urban planning, job locations, housing, and policy is an example of:", options:["Nested systems working at multiple levels","Only one isolated event","A closed chemical experiment","A single tangible object"], correct:0 },
                { id:"B8", text:"If one department improves road width but public transport remains poor, traffic may still continue because:", options:["Improving one subsystem may not improve the whole system","Roads are not part of transport systems","Public transport cannot affect traffic","Systems have no purpose"], correct:0 },
                { id:"B9", text:"Which option best represents a wider boundary for traffic analysis?", options:["Cars, roads, public transport, land use, parking, work timings, and citizen behaviour","Only cars","Only traffic police uniforms","Only one road intersection"], correct:0 },
                { id:"B10", text:"The main lesson from this case is:", options:["How we draw the boundary changes the solution we can see","Boundaries do not matter in systems thinking","External factors never affect systems","Closed systems are the best way to study cities"], correct:0 }
            ]
        },
        {
            id: "C", title: "Iceberg Model, Events, Patterns, Structure & Mental Models", subtitle: "10 Case-Based MCQs",
            caseParagraph: `A college food court becomes overcrowded every day between 12:00 pm and 1:00 pm. At first, the administration reacts by telling students to stand properly in lines. But crowding continues daily. After studying the issue, they find that all classes end at the same time, the lunch break is short, there are only five vendors, and seating is limited. Students also believe that eating immediately after class is necessary because they may not get time later. The administration realizes that the visible crowd is only the event, while repeated crowding, schedule design, vendor capacity, seating limits, and beliefs are deeper layers of the problem.`,
            type: "mcq",
            questions: [
                { id:"C1", text:"The visible crowd at 12:30 pm on one day is an example of:", options:["Event","Mental model","Paradigm","Dynamic equilibrium"], correct:0 },
                { id:"C2", text:"Crowding happening every day between 12:00 pm and 1:00 pm shows:", options:["A pattern of behaviour over time","Only one isolated incident","A closed system","A stock-flow rule"], correct:0 },
                { id:"C3", text:"Same class ending time, short lunch break, limited vendors, and fewer seats represent:", options:["System structure causing the repeated crowding","Only mental models with no physical effect","An outflow from a stock","A Nash equilibrium only"], correct:0 },
                { id:"C4", text:`The belief "I must eat immediately because I will not get time later" is a:`, options:["Mental model affecting student behaviour","Physical flow of food","Closed system boundary","Material stock"], correct:0 },
                { id:"C5", text:"Which question is most aligned with the Iceberg Model?", options:["What deeper structure creates the daily food court crowding?","Which student stood first today?","Which table colour is best?","How can we ignore lunch patterns?"], correct:0 },
                { id:"C6", text:"Telling students only to stand properly in lines may fail because:", options:["It reacts to the event but does not change the structure creating the pattern","It changes the deepest mental model immediately","It increases vendor capacity automatically","It removes all feedback loops"], correct:0 },
                { id:"C7", text:"Which solution targets system structure better?", options:["Stagger lunch breaks and increase service capacity","Blame only students","Ignore seating limits","Make one announcement and stop analysis"], correct:0 },
                { id:"C8", text:"Which Iceberg order is correct?", options:["Events → Patterns → System Structure → Mental Models","Mental Models → Events → Patterns → Structure","Structure → Events → Mental Models → Patterns","Patterns → Events → Mental Models → Stock"], correct:0 },
                { id:"C9", text:"If the college studies crowding data across the whole semester, it is moving from:", options:["Event-level reaction to pattern-level understanding","Mental model to closed system","Stock to source","Flow to sink"], correct:0 },
                { id:"C10", text:"The deepest long-term change would involve:", options:["Redesigning schedules and changing beliefs about lunch timing","Only shouting at students daily","Ignoring vendor limits","Measuring only one day's crowd"], correct:0 }
            ]
        },
        {
            id: "D", title: "System Archetypes, Feedback Loops & Game Theory", subtitle: "10 Case-Based MCQs",
            caseParagraph: `Two students are working on a group project. Both know that if they work equally, the final project will be strong and both will get good marks. However, each student privately thinks, "If the other person works, I can reduce my effort and still get marks." As both students think this way, both reduce effort. The project quality falls. Later, each student blames the other. The teacher adds stricter deadlines, but students still divide work unfairly because the grading system gives the same marks to everyone, regardless of individual contribution.`,
            type: "mcq",
            questions: [
                { id:"D1", text:"This case is best understood through Game Theory because:", options:["Each student's best decision depends on what the other student does","The project has no strategy or incentive","Students are not connected in any way","Game theory only studies weather systems"], correct:0 },
                { id:"D2", text:"If each student reduces effort to protect their own benefit, this is an example of:", options:["Individual rationality","Collective rationality","Dynamic equilibrium only","Information flow only"], correct:0 },
                { id:"D3", text:"If both students work equally for a strong project, that would be:", options:["Collective rationality","Outflow","Reality bias","Closed system behaviour"], correct:0 },
                { id:"D4", text:"The bad outcome becomes stable because neither student wants to work more alone while the other free-rides. This resembles:", options:["Nash equilibrium","System boundary","Tangible element","Dynamic equilibrium in a water tank"], correct:0 },
                { id:"D5", text:"The same marks for unequal contribution creates a problem in:", options:["Incentive structure","Physical material flow","Weather environment only","Stock-flow notation"], correct:0 },
                { id:"D6", text:`"Less effort → lower project quality → more blame → less cooperation" can become:`, options:["A reinforcing loop that worsens teamwork","A balancing loop that always improves quality","A closed system with no feedback","A buffer stock"], correct:0 },
                { id:"D7", text:"Stricter deadlines may not solve the problem if they do not change:", options:["The grading structure and accountability system","The project file name only","The classroom wall colour","The number of pages only"], correct:0 },
                { id:"D8", text:"Which system archetype may appear if stricter deadlines give temporary improvement but unfair work continues later?", options:["Fixes That Fail","Tragedy of Commons only","Limits to Success only","Closed system"], correct:0 },
                { id:"D9", text:"A better intervention would be:", options:["Individual contribution tracking and peer evaluation","Same marks regardless of contribution","Only verbal warnings","Ignoring group dynamics"], correct:0 },
                { id:"D10", text:"The main systems lesson from this case is:", options:["Bad outcomes can come from incentives and structure, not only from personal laziness","Group projects have no system structure","Individual choices never affect collective outcomes","Feedback loops are not useful in teamwork"], correct:0 }
            ]
        },
        {
            id: "E", title: "Long Case Study — Fill in the Blanks", subtitle: "20 Keyword-Based Questions",
            caseParagraph: `A university observed that many students were struggling with focus and academic performance. On some days, students missed deadlines or performed poorly in quizzes. At first, teachers treated these as individual events and blamed students for lack of discipline. However, when the university studied the issue over the semester, it found a repeated pattern: phone usage increased during low-pressure weeks, study hours decreased, sleep quality reduced, and stress increased near exams.\n\nThe system had many connected parts. Students, smartphones, social media apps, assignments, exams, teachers, peer groups, hostel routines, and family expectations were all elements of the system. Some elements were tangible, such as phones and classrooms. Others were intangible, such as motivation, attention, habits, trust, culture, and beliefs.\n\nThe interconnections were also important. More phone usage reduced study hours. Less study increased stress. More stress reduced sleep quality. Poor sleep reduced focus. Lower focus reduced learning, which again increased stress. This created a reinforcing loop. Some students tried to control the problem by deleting apps during exams, but after exams they downloaded them again. This gave temporary relief but did not solve the deeper habit structure.\n\nThe university also found different mental models. Students believed, "I can manage everything before exams." Teachers believed, "Students are careless." Parents believed, "Students need stricter rules." But the university realized the problem was systemic. Long-term change required better time management support, healthier hostel routines, classroom engagement, student self-awareness, and changing the belief that last-minute study is enough.`,
            type: "fib",
            keywords: ["Systems Thinking","System","Elements","Tangible Elements","Intangible Elements","Interconnections","Information Flow","Purpose","System Boundary","Environment","Open System","Subsystem","Nested Systems","Iceberg Model","Event","Pattern","System Structure","Mental Model","Feedback Loop","Reinforcing Loop","Balancing Loop","System Archetype","System Trap","Fixes That Fail","Variable","BoT Graph","Loop Dominance","Problem Formulation","Long-Term Solution"],
            questions: [
                { id:"E1", text:"Understanding digital distraction by studying students, phones, apps, sleep, stress, and learning together is called __________.", answer:"Systems Thinking", acceptableAnswers:["systems thinking"] },
                { id:"E2", text:"The university distraction issue is a __________ because many connected parts interact and produce behaviour over time.", answer:"System", acceptableAnswers:["system"] },
                { id:"E3", text:"Students, smartphones, assignments, teachers, and exams are examples of system __________.", answer:"Elements", acceptableAnswers:["elements","element"] },
                { id:"E4", text:"Phones, classrooms, and physical study spaces are __________ because they can be seen or touched.", answer:"Tangible Elements", acceptableAnswers:["tangible elements","tangible element"] },
                { id:"E5", text:"Motivation, attention, habits, culture, trust, and beliefs are __________ because they are invisible but powerful.", answer:"Intangible Elements", acceptableAnswers:["intangible elements","intangible element"] },
                { id:"E6", text:`The relationship "more phone usage reduces study hours" is an example of __________ between elements.`, answer:"Interconnections", acceptableAnswers:["interconnections","interconnection"] },
                { id:"E7", text:"Missed deadlines or poor quiz performance on a specific day are visible __________.", answer:"Event", acceptableAnswers:["event","events"] },
                { id:"E8", text:"Phone usage rising in low-pressure weeks and stress rising near exams every semester shows a repeated __________.", answer:"Pattern", acceptableAnswers:["pattern","patterns"] },
                { id:"E9", text:"Hostel routine, assignment timing, app design, and exam pressure together form the deeper __________ behind the pattern.", answer:"System Structure", acceptableAnswers:["system structure","structure"] },
                { id:"E10", text:`The belief "I can manage everything before exams" is a __________.`, answer:"Mental Model", acceptableAnswers:["mental model","mental models"] },
                { id:"E11", text:"The tool that helps move from events to patterns, structures, and mental models is the __________.", answer:"Iceberg Model", acceptableAnswers:["iceberg model"] },
                { id:"E12", text:"Phone usage, study hours, stress level, sleep quality, and focus are __________ because they change over time.", answer:"Variable", acceptableAnswers:["variable","variables"] },
                { id:"E13", text:"A graph showing stress level across the semester would be a __________.", answer:"BoT Graph", acceptableAnswers:["bot graph","bot","behaviour over time graph","behavior over time graph"] },
                { id:"E14", text:`"More phone usage → less study → more stress → less focus → even less study" is a __________ because the effect comes back and strengthens the problem.`, answer:"Feedback Loop", acceptableAnswers:["feedback loop","feedback loops"] },
                { id:"E15", text:"The same loop is specifically a __________ because it amplifies the original problem.", answer:"Reinforcing Loop", acceptableAnswers:["reinforcing loop","reinforcing feedback loop","r loop"] },
                { id:"E16", text:"If high stress pushes students to study more and reduce stress, that would be a __________.", answer:"Balancing Loop", acceptableAnswers:["balancing loop","balancing feedback loop","b loop"] },
                { id:"E17", text:"Deleting apps only during exams gives temporary relief but the problem returns; this is an example of __________.", answer:"Fixes That Fail", acceptableAnswers:["fixes that fail","fix that fail"] },
                { id:"E18", text:"Fixes That Fail is a type of __________ because it is a repeated problem pattern.", answer:"System Archetype", acceptableAnswers:["system archetype","archetype"] },
                { id:"E19", text:`A clear statement such as "student stress increases sharply during exam weeks due to low preparation" is an example of __________.`, answer:"Problem Formulation", acceptableAnswers:["problem formulation","problem statement"] },
                { id:"E20", text:"Changing study habits, hostel routine, classroom engagement, and beliefs together can create a __________.", answer:"Long-Term Solution", acceptableAnswers:["long-term solution","long term solution"] }
            ]
        }
    ]
};
